# syntax=docker/dockerfile:1.4
FROM node:20-bookworm

WORKDIR /app

# Copy package.json + package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy toàn bộ code
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
